services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
     - 3000:3000
    volumes:
     - grafana-storage:/var/lib/grafana
    networks:
      - obs
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    volumes:
     - db-data:/var/lib/postgresql/data
    ports:
     - 5432:5432
    networks:
     - obs
  golang:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: golang
    restart: always
    networks:
      - obs
    ports:
     - 9000:9000
    depends_on:
     - db
    environment:
     - DB_URI=postgres://db:root@password/test
  prometheus:
    image: prom/prometheus:latest
    volumes:
     - ./prometheus:/etc/prometheus/
     - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
     - 9090:9090
    restart: always
    networks:
     - obs

volumes:
  grafana-storage:
  prometheus_data:
  db-data:

networks:
  obs: